### ISSUE TITLE
Create a custom provider for AwsRegionProviderChain

### ISSUE THREAD

**Issue by ptirador** [carlspring/s3fs-nio#100]
# Task Description
The `S3Factory` class manages the build of a new Amazon S3 instance, which needs a region. This is provided by getting it from a properties file, and, in the case there's no property defined, the region is obtained by using a default region provider chain.

As specified in this [Pull Request discussion](https://github.com/carlspring/s3fs-nio/pull/83#discussion_r504156952), although it's highly unlikely, there could be a different region provider chain needed by a consumer of the API (this would have to be custom, as the SDK only has Default). Might want to provide a customization option for this, rather than hard coding `new DefaultAwsRegionProviderChain`.

# Tasks

The following tasks will need to be carried out:
* [ ] Create a custom provider class `org.carlspring.cloud.storage.s3fs.S3AwsRegionProviderChain`.
* [ ] This class must extend from `software.amazon.awssdk.regions.providers.AwsRegionProviderChain`.
* [ ] This class must have a constructor which will call its parent constructor to define a list of region providers, which will be (for the moment), in this order: 
`software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider`
`software.amazon.awssdk.regions.providers.AwsProfileRegionProvider`
* [ ] `getRegion` method should not be overridden, so method from parent will be used.
* [ ] Use this new provider chain in `org.carlspring.cloud.storage.s3fs.S3Factory` class, `getRegion`method, by replacing the `DefaultAwsProviderChain` with the new one.

# Task Relationships

This task:
* Is a follow-up of: #63 

# Useful Links

* [AWS Region Selection](https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/java-dg-region-selection.html)

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @steve-todorov
  * @sbespalov

**Comment by pyashwanthkumar** [comment]
where should the class AwsRegionProviderChain be created? the only method of this class would be to get the region from user and setting it?

**Comment by ptirador** [comment]
@pyashwanthkumar I've updated the issue description with a most specific tasks list. Hope it helps.
