### ISSUE TITLE
Re-work the way the configuration works

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#116]
# Task Description

The current way that the configuration is implemented is quite confusing and error-prone to work with. We need to clarify how we'd like this to work, gather the requirements and refactor this.

# Tasks

The following tasks will need to be carried out:
* [ ] Define our use cases.
* [ ] Collect a list of problems with the current implementation.
* [ ] Refactor the code.
* [ ] Update the documentation.

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @steve-todorov
  * @sbespalov

**Comment by carlspring** [comment]
@ptirador , @steve-todorov , @elerch, @markjschreiber, @pditommaso ,

Please, feel free to join in and share your thoughts on this topic! :)

@elerch, @markjschreiber: I know you had some first hand experience in this regard, as well as a passionate disliking of how it currently works, which would be quite helpful in defining how to re-implement and do it better.
