### ISSUE TITLE
Integration tests must clean up after execution

### ISSUE THREAD

**Issue by steve-todorov** [carlspring/s3fs-nio#120]
# Task Description

The integration tests currently leave behind the resources they have created without cleaning up after the execution.
We should improve this so that when you test with a real S3 bucket, it cleans up and reduces any costs for hosting.

Currently, these tests are using constructs like this to generate random names for the files:
```
Path file = fileSystemAmazon.getPath(bucket, UUID.randomUUID().toString());
```
While this does do the job, there is no way to actually clean up, unless we can invoke a "delete all" operation against the S3 bucket via the AWS SDK. This is inefficient.

We can do something like what we've done in our [strongbox](https://github.com/strongbox/strongbox/) project. In essence, thanks to @sbespalov, we have implemented annotations (and a mechanism around them) for creating test repositories and test artifacts. These are created for every test method and then disposed of, once it's completed (there is an option to preserve these, of course, if required for debugging purposes).

## Classes of Interest From The Strongbox Project

* [@TestArtifact](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/artifact/TestArtifact.java)
* [TestArtifactContext](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/artifact/TestArtifactContext.java)
* [ArtifactManagementTestExecutionListener](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/artifact/ArtifactManagementTestExecutionListener.java)
* [RepositoryManagementTestExecutionListener](https://github.com/strongbox/strongbox/blob/master/strongbox-storage/strongbox-storage-api/src/test/java/org/carlspring/strongbox/testing/storage/repository/RepositoryManagementTestExecutionListener.java)

# Task List

* [ ] Research what needs to be done and whether we can do it without Spring, or if it would require it. Perhaps we could add `spring-test` to the mix just for this, without having to turn this project into one that requires Spring as a runtime dependency.
* [ ] Implement a `@S3TestPath` annotation.
* [ ] Implement a `S3TestPathContext`. The path can still use UUID-s for this, but this way they'll be tracked and removed.
* [ ] Implement a `S3TestPathExecutionListener`.
* [ ] Re-work the test cases
  * [ ] `org.carlspring.cloud.storage.s3fs.path.ToURLIT`
  * [ ] `org.carlspring.cloud.storage.s3fs.S3ClientIT`
  * [ ] `org.carlspring.cloud.storage.s3fs.FilesIT`
  * [ ] `org.carlspring.cloud.storage.s3fs.spike.EnvironmentIT`
  * [ ] `org.carlspring.cloud.storage.s3fs.ExampleClassIT`
  * [ ] `org.carlspring.cloud.storage.s3fs.fileSystemProvider.NewFileSystemIT`
  * [ ] `org.carlspring.cloud.storage.s3fs.fileSystemProvider.GetFileSystemIT`
  * [ ] `org.carlspring.cloud.storage.s3fs.fileSystemProvider.NewByteChannelIT`
  * [ ] `org.carlspring.cloud.storage.s3fs.S3UtilsIT`
  * [ ] `org.carlspring.cloud.storage.s3fs.FileSystemsIT`

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @steve-todorov
  * @ptirador

**Comment by sbespalov** [comment]
@steve-todorov we already have `@TestRepository#cleanup()` for this. You mean that it doesn't work properly?

**Comment by carlspring** [comment]
I think you're mixing up the projects @sbespalov . We're not using this here.

**Comment by sbespalov** [comment]
Ok

чт, 26 нояб. 2020 г., 17:13 Martin Todorov <notifications@github.com>:

**Comment by steve-todorov** [comment]
I'm putting this task on hold for a moment - although it would be nice for tests to clean-up after execution this means more API requests will be used. This, in turn, we'd use our free S3 tire faster. It looks like we could fix this issue by setting a `Lifecycle rule` which expires and deletes all objects in the bucket after X days. 

I'll be trying this out soon - meanwhile, this task is on hold unless somebody would like to make the clean-up part configurable.

**Comment by steve-todorov** [comment]
Setting `Lifecycle rules` does the job at no additional cost. In combination with https://github.com/carlspring/s3fs-nio/pull/200 concurrency issues are virtually non-existing so closing as won't fix.
