### ISSUE TITLE
Convert the configuration properties to use dots instead of underscores

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#136]
# Task Description

We should convert all the properties to use dots instead of underscores, as this is the real Java convention.

How it looks currently:
* `amazon.properties`
```
bucket_name=/bucket
s3fs_access_key=AKIAEXAMPLEKEY
s3fs_secret_key=fadf3rafsadf3r23wafsdf9i209ifs
s3fs_region=eu-west-2
s3fs_protocol=https
```

How it should look:
* `amazon.properties`
```
s3fs.bucket.name=/bucket
s3fs.access.key=AKIAEXAMPLEKEY
s3fs.secret.key=fadf3rafsadf3r23wafsdf9i209ifs
s3fs.region=eu-west-2
s3fs.protocol=https
```

# Tasks

The following tasks will need to be carried out:
* [ ] Convert the properties to use dots instead of underscores.
* [ ] Make the necessary changes to the code.
* [ ] Rename the `bucket_name` property to `s3fs.bucket.name`.
* [ ] Update the documentation.

# Task Relationships

This task:
* Relates to: #116

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @ptirador
  * @steve-todorov
  * @sbespalov
