### ISSUE TITLE
Re-work the configuration properties to support multiple buckets, credentials and regions

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#137]
# Task Description

At the moment, it's not possible to use multiple buckets, credentials and regions. In a more sophisticated application this would be quite a limitation.

The format of the `amazon.properties` currently looks like this:
```
bucket_name=/bucket
s3fs_access_key=AKIADEMOACCESSKEY
s3fs_secret_key=sfsoj291aSFfasfsafs1fsa1
s3fs_region=eu-west-2
s3fs_protocol=https
```

Once #136 has been implemented, (and the underscores in the properties have been converted to dots), we should consider doing something like this:
```
s3fs.${configurationName}.bucket.name=/bucket
s3fs.${configurationName}.access.key=AKIADEMOACCESSKEY
s3fs.${configurationName}.secret.key=sfsoj291aSFfasfsafs1fsa1
s3fs.${configurationName}.region=eu-west-2
s3fs.${configurationName}.protocol=https
```

For example:
```
s3fs.filestore1.bucket.name=/bucket
s3fs.filestore1.access.key=AKIADEMOACCESSKEY
s3fs.filestore1.secret.key=sfsoj291aSFfasfsafs1fsa1
s3fs.filestore1.region=eu-west-2
s3fs.filestore1.protocol=https
```

# Tasks

The following tasks will need to be carried out:
* [ ] Re-work the properties file for the tests.
* [ ] Implement the necessary changes to the code.
* [ ] Update the documentation.

# Task Relationships

This task:
* Depends on: #136 
* Relates to: #116

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @ptirador
  * @steve-todorov
  * @sbespalov
