### ISSUE TITLE
Investigate if and how we can extract the integration tests into suites

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#140]
# Task Description

At the moment, the integration tests are executed as separate tests using the `maven-failsafe-plugin`. We need to re-work this so that they are executed as a suite. This needs to be done so that we could be able to re-run the same integration tests against different environments. For example, the default profile for integration tests should be against a real Amazon S3. However, if we re-work these to be executed as a suite, we could then add another suite with the same tests, but for MinIO instead.

What we can do is:
* Have all the integration tests that are connecting to S3 tagged using the `@Tag("integration-test-s3")` annotation.
* Create separate test suites that have an `@IncludeTags("integration-test-s3")` annotation
* Create an `AmazonS3ITTestSuite`.
* Eventually, create additional test suites such as, for example, `MinIOITTestSuite`.
* Make the `maven-failsafe-plugin` only execute the `*ITSuite` classes.

# Tasks

The following tasks will need to be carried out:
* [x] Investigate whether it's possible to enable/trigger profiles for JUnit tests at a suite level.
* [x] Create a test suite for all the integration tests.
* [x] Make the `maven-failsafe-plugin` only execute `*ITSuite`-s.

# Task Relationships

This task:
* Relates to: #103 
* Depends on:
  * junit-team/junit5#744 (supposed to be fixed via junit-team/junit5#2416)
  * junit-team/junit5#2503

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @ptirador
  * @steve-todorov
  * @sbespalov

**Comment by carlspring** [comment]
We'll have to re-visit this topic once junit-team/junit5#744 (supposed to be fixed via junit-team/junit5#2416) have been impemented, so that we could drop the JUnit4 dependencies.

**Comment by carlspring** [comment]
Eventually, when #60 and #103 have been implemented, we'll create a new suite for MinIO.
