### ISSUE TITLE
Implement support for deleting directories recursively

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#163]
# Task Description

We need to implement support for deleting directories recursively in the `org.carlspring.cloud.storage.s3fs.S3FileSystemProvider` class, as this currently only works for regular files, or empty directories and does not recurse into directories, nor remove any files that exist in them.

# Tasks

The following tasks will need to be carried out:
* [ ] Study the code of the `org.carlspring.cloud.storage.s3fs.S3FileSystemProvider` and propose the most efficient way to do this.
* [ ] Implement the necessary changes.
* [ ] Implement test cases.

# Useful links

* [Blog - Multi-Object Delete Announcement](https://aws.amazon.com/about-aws/whats-new/2011/12/07/amazon-s3-announces-multi-object-delete/#:~:text=We%20are%20excited%20to%20announce,your%20application%20and%20Amazon%20S3.)
* [Dev Guide - Multi-Object Delete Docs and Examples](https://docs.aws.amazon.com/AmazonS3/latest/dev/DeletingMultipleObjects.html)
* [Dev Guide - Deleting objects](https://docs.aws.amazon.com/AmazonS3/latest/dev/DeletingObjects.html)
* [Dev Guide - Listing Keys Hierarchically Using a Prefix and Delimiter](https://docs.aws.amazon.com/AmazonS3/latest/dev/ListingKeysHierarchy.html)
* [API Delete Objects](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html)

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @ptirador
  * @steve-todorov
  * @sbespalov

**Comment by steve-todorov** [comment]
The [docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/DeletingObjects.html) state there's a limit for deleting multiple objects:

> Delete multiple objects—Amazon S3 also provides the Multi-Object Delete API that you can use to delete up to 1000 objects in a single HTTP request.

"Directories" can contain much more than 1000 objects and they can be nested (which also counts as an object within the parent). The way I see this working would be to have something like this:

1. A method which [Lists Keys Hierarchically Using a Prefix and Delimiter](https://docs.aws.amazon.com/AmazonS3/latest/dev/ListingKeysHierarchy.html) should return a portion of the records for the path which is going to be deleted. The docs don't state it, but the source code mentions there's a limit of `1000 objects` as well.
  ```
  // s3-2.15.57.jar/codegen-resources/service-2.json 
  "ListObjectsV2Request" { 
     ...
     "MaxKeys":{
        "shape":"MaxKeys",
        "documentation":"<p>Sets the maximum number of keys returned in the response. By default the API returns up to 1,000 key names. The response might contain fewer keys but will never contain more.</p>",
        "location":"querystring",
        "locationName":"max-keys"
     }
     ...
  },
  ```

2. A method which does multi-object deletion following the [Deleting Multiple Objects](https://docs.aws.amazon.com/AmazonS3/latest/dev/DeletingMultipleObjectsUsingJava.html) example

3. `while(continue != false) deleteObjects; listObjects = getObjects(); continue = listObjects.size() > 0;`

4. If there are errors during the deletion - I would assume the operation should stop (unless a `force=true` argument was provided?)

**Comment by dmndZhWng** [comment]
@steve-todorov concerning the 4.
As the delete(...) method from S3FileSystemProvider is inherited from java.nio.file.spi.FileSystemProvider:
`public abstract void delete(Path path) throws IOException;`
the boolean `force=true` could not be used as argument in the method ... :/

Maybe we could : 
- throw the SdkException at S3FileSystemProvider::delete level (hence, let the user to decide how to handle that case) ? 
- or wrap it and throw it as an IOException in order to keep only 1 base exception for the delete method ?

any idea/suggestion is welcomed.
