### ISSUE TITLE
Use tags instead of suites to separate tests

### ISSUE THREAD

**Issue by steve-todorov** [carlspring/s3fs-nio#183]
# Task Description

In #140 we introduced the concept of "suites". Unfortunately this doesn't seem to be working very well and the unit tests are not being triggered at all. Furthermore, it has complicated our dependencies since we also need to use `JUnit 4` to run those "suites": 

```
@RunWith(JUnitPlatform.class)
@IncludeTags({ "s3-integration-test" })
@SelectPackages({ "org.carlspring.cloud.storage.s3fs" })
public class AmazonS3ITSuite {}

/** 
 * ......
 * Please note that test classes and suites annotated with
 * @RunWith(JUnitPlatform.class) cannot be executed directly on
 * the JUnit Platform (or as a "JUnit 5" test as documented in some IDEs). Such
 * classes and suites can only be executed using JUnit 4 infrastructure.
 * ......
 */
org.junit.platform.runner.JUnitPlatform 
{
}
```

Since there is no official support for suites yet (junit-team/junit5#744 which is supposed to be fixed via junit-team/junit5#2416), we will have to fall back to simply `@Tag` instead.

# Tasks

The following tasks will need to be carried out:

* [x] Revert changes made via #140.
* [x] Create `MinioIntegrationTest` and `S3IntegrationTest` annotations which can be used per class or method
* [x] Setup proper profiles which run these annotations
* [x] Tag integration tests with the appropriate annotation
* [x] Make sure build actually `fails` when there NO tests run to prevent false-positive green builds
* [x] Run integration tests in GH Actions.
* [x] Change gh issue templates to use `-Pit-s3` instead of `-Pintegration-tests`
* [ ] Change documentation to use `-Pit-s3` instead of `-Pintegration-tests`

# Task Relationships

This task:
* Relates to: #140

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @ptirador
  * @steve-todorov
  * @sbespalov
