### ISSUE TITLE
Implement an S3FileSystemConfiguration

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#195]
# Task Description

The current implementation of the configuration is not flexible enough. It also requires you to pass properties around. The way that the properties are loaded for testing and production is different. We should implement a `S3FileSystemConfiguration` and use this instead of the properties/hash maps.

# Tasks

The following tasks will need to be carried out:
* [ ] Create an `S3FileSystemConfiguration` and add all the meaningful property keys as fields in this class.
* [ ] Implement a `from(Map<String, ?> map)` constructor.
* [ ] Implement a `from(Properties properties)` constructor.
* [ ] Implement a `public Map<String, String> asMap()`.
* [ ] Implement a `public Properties asProperties()`.

# Task Relationships

This task:
* Is a sub-task of: #194

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @ptirador
  * @steve-todorov
  * @sbespalov
