### ISSUE TITLE
Drop the heavy use of Properties all over the place and replace it with the S3FileSystemConfiguration

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#196]
# Task Description

Once #195 has been implemented, we need to refactor the code for the `S3FileSystemProvider` and `S3FileSystem` as necessary so that we can drop the heavy use of properties.

# Tasks

The following tasks will need to be carried out:
* [ ] Assess what will need to be done and update this task, if and as necessary
* [ ] Carry out the refactoring.
* [ ] Fix any broken tests.

# Task Relationships

This task:
* Is a sub-task of: #194 
* Depends on: #195 

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @ptirador
  * @steve-todorov
  * @sbespalov
