### ISSUE TITLE
Re-work the S3FileSystem to not require you to specify the bucket and resolve this from the S3FileSystemConfiguration instead

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#197]
# Task Description

Once #195 and #196 have been implemented, we need to change how the `S3FileSystem` and `S3FileSystemProvider` work, so that they no longer need you to specify the bucket (and resolve this from the `S3FileSystemConfiguration` instead).

The following code across the code base:
```java
S3Path path = s3FileSystem.getPath("/bucketA", "dir");

```
Should then be simplified to:
```java
S3Path path = s3FileSystem.getPath("dir");
```

# Tasks

The following tasks will need to be carried out:
* [ ] Assess what will need to be done and update this task, if and as necessary.
* [ ] Carry out the refactoring.
* [ ] Fix any broken tests.

# Task Relationships

This task:
* Is a sub-task of: #194
* Depends on: #195, #196

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @ptirador
  * @steve-todorov
  * @sbespalov
