### ISSUE TITLE
Set up badges

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#21]
# Task Description

We should gather a list of badges that we'd like to display such as:
* [x] Maven
* [x] License
* [x] Build status
* [x] ~~Number of tests~~ no such option in Github Actions.
* [x] Chat channel
* [x] SonarQube quality gate badge

# Tasks

The following tasks will need to be carried out:
* [x] Add badges for the above.

**Comment by steve-todorov** [comment]
Fixed as part of #70
