### ISSUE TITLE
Set up a project documentation site using mkdocs and publish it to github.io

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#22]
# Task Description

We should set up a proper wiki with searchable/indexable examples.

# Tasks

The following tasks will need to be carried out:
* [ ] Set up a github.io site. 
* [ ] Set build a minimal documentation site using `mkdocs`.
* [ ] Set up Netlify for previewing pull requests.
