### ISSUE TITLE
Translate all comments, methods, vars, etc that are in Spanish into English

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#53]
# Task Description

As the original authors were Spanish native-speakers, there are a lot of comments, variables, etc in the code that are in Spanish. We should translate these in English, so that it's clearer for other contributors that don't speak Spanish.

The code base is not that large, so going through it (both sources and resource files) should not take too long.

# Tasks

The following tasks will need to be carried out:
* [ ] Translate all comments from Spanish to English.
* [ ] Translate all variables from Spanish to English.
* [ ] Translate all methods from Spanish to English.

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio2-community)
* Points of contact:
  * @carlspring
  * @steve-todorov
  * @sbespalov

**Comment by viveksahu26** [comment]
I would like to work on this issue.. Please assign me..

**Comment by carlspring** [comment]
Thanks, @viveksahu26 , but do you actually speak Spanish?

**Comment by viveksahu26** [comment]
Little bit i know.. But, I will definitily  mange it..

**Comment by carlspring** [comment]
Okay, as long as it's not run through Google Translate! :)

**Comment by viveksahu26** [comment]
Don't worry sir.. I will keep this in my mind..

**Comment by carlspring** [comment]
En ese caso -- buena suerte! ;)

**Comment by viveksahu26** [comment]
Gracias !!

**Comment by viveksahu26** [comment]
@carlspring , I would like to inform you  that each comments, Methods , variables , etc. are already converted into English from Spanish language.. So , there is no need of making any changes..

**Comment by carlspring** [comment]
...This leads me to believe you haven't really gone over the code throughly enough.

**Comment by viveksahu26** [comment]
If you are so sure can you show me the code written in spanish..

**Comment by carlspring** [comment]
Well, we need this to be looked at and read throughly. If I were to list all the places, then I might just as well do it myself.

Here's an example, and there are other places where I've seen these. They're also in variables.
* `org.carlspring.cloud.storage.s3fs.util.CopyDirVisitor`:
```java
        // sacamos el path relativo y lo recorremos para
        // añadirlo al nuevo
        for (Path path : fromPath.relativize(to))
        {
            // si utilizamos path en vez de string: lanza error por ser
            // distintos paths
            targetPath = targetPath.resolve(path.getFileName().toString());
        }
```

**Comment by viveksahu26** [comment]
Definitely , I will go through it again and again.. By the way thanks.

**Comment by viveksahu26** [comment]
Please help me to resolve this test case..

[I am unable to get this issue.](https://github.com/carlspring/s3fs-nio2/pull/65/checks?check_run_id=1038395132)

**Comment by ptirador** [comment]
Hi @carlspring, can I take this? The related PR seems stopped from more than a month and I could do this quickly.

**Comment by carlspring** [comment]
Yes, please!
