### ISSUE TITLE
Set up a release pipeline

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#691]
# Task Description

We need to set up a release pipeline.

# Tasks

The following tasks will need to be carried out:
* [x] ~Generate a new GPG key and upload it to the key servers.~
* [x] Investigate how to properly limit the access to those who can execute releases.
* [x] Decide whether to use Github Actions, or Jenkins.
* [x] Set up a pipeline that creates a release and deploys to Maven Central.
* [x] Update the documentation.
* [x] Update backlinks:
  * [x] Notify the folks on aws/aws-sdk-java-v2#1388 that we've published a release.
  * [x] Add a new answer to [Stackoverflow: Java NIO File Implementation For AWS](https://stackoverflow.com/questions/41113119/java-nio-file-implementation-for-aws/74604812#74604812) with a link to our documentation.
* [x] Test
  * [x] The release is available for download via Maven Central.

# Task Relationships

This task:
* Is a sub-task of:
* Depends on:
* Is a follow-up of:
* Relates to:
  * #54 
  * #577 

# Useful Links

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @steve-todorov
