### ISSUE TITLE
Set up versioned mkdocs documentation

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#707]
# Task Description

We should look into implementing versioned docs using `mkdocs`, to keep the historical documenation for the different releases.

# Tasks

The following tasks will need to be carried out:
* [ ] Investigate what needs to be done.
* [ ] Make the necessary changes on the `mkdocs` side.
* [ ] Make the necessary changes to the Github workflow.

# Task Relationships

This task:
* Is a sub-task of:
* Depends on:
* Is a follow-up of:
* Relates to:

# Useful Links

* [Mkdocs: Setting up versioning](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/)

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @steve-todorov
