### ISSUE TITLE
Assemble a list of the pull requests of Upplication/Amazon-S3-FileSystem-NIO2 and evaluate them

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio#72]
# Task Description

While [Upplication/Amazon-S3-FileSystem-NIO2](https://github.com/Upplication/Amazon-S3-FileSystem-NIO2) seems abandoned, there appear to be quite a few open pull requests. We should see if there are any of them that we would like to apply to our project and reach out to the respective contributors to ask them, if they'd like to contribute them back to our project.

This is the master task. The actual work should be split into sub-tasks and be added to the list below.

# Tasks

The following tasks will need to be carried out:
* [ ] Review and apply Upplication/Amazon-S3-FileSystem-NIO2#114 : Fixing POSIX file attributes (permissions, owner) for directories and bucket root; work required to get sftp cd command working with Apache Mina SSHD
* [ ] Review and apply Upplication/Amazon-S3-FileSystem-NIO2#117 : Fixed URI encoding with special characters
* [ ] Review and apply Upplication/Amazon-S3-FileSystem-NIO2#119 : Make sure S3FileSystemProvider.readAttributes() sees a newly created file
* [ ] Review and apply Upplication/Amazon-S3-FileSystem-NIO2#121 : Allow longer filenames to be uploaded to S3
* [ ] Review and apply Upplication/Amazon-S3-FileSystem-NIO2#128 : Implement directory copy with similar semantics as NIO2
* [ ] Review and apply Upplication/Amazon-S3-FileSystem-NIO2#131 : Add support for transparent server side encryption
* [ ] Review and apply Upplication/Amazon-S3-FileSystem-NIO2#113 : If the attrs.isDirectory, give it full permissions control, so we don't get a NullPointerException because we did not initialize the permissions
* [ ] Review and apply Upplication/Amazon-S3-FileSystem-NIO2#110 : S3 multipart upload
* [ ] Review and apply Upplication/Amazon-S3-FileSystem-NIO2#107 : Make owner optional when fetching attributes
* [ ] Review and apply Upplication/Amazon-S3-FileSystem-NIO2#104 : More robust S3Path.resolve
* [ ] Review and apply Upplication/Amazon-S3-FileSystem-NIO2#102 : Restrict use of AmazonS3.listBuckets()
* [ ] Review and apply Upplication/Amazon-S3-FileSystem-NIO2#97 : Support for user-specified AWS credential providers
* [ ] Review and apply Upplication/Amazon-S3-FileSystem-NIO2#96 : Added directory permissions to improve SFTP compatibility
* [ ] Review and apply Upplication/Amazon-S3-FileSystem-NIO2#95 : Added support for specifying KMS key ID as s3fs_kms_key_id
* [ ] Review and apply Upplication/Amazon-S3-FileSystem-NIO2#91 : Implemented FileTypeDetector to return contentType from Metadata (possibly together with Upplication/Amazon-S3-FileSystem-NIO2#85 : add FileTypeDetector?)
* [ ] Review and apply Upplication/Amazon-S3-FileSystem-NIO2#45 : Introduce S3OutputStream that uploads data to S3 directly

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @steve-todorov
  * @sbespalov
