### ISSUE TITLE
Improve github build 

### ISSUE THREAD

**Issue by steve-todorov** [carlspring/s3fs-nio#76]
# Task Description

- [x]  Merge jobs into one instead of one for build and one for analysis.
- [x] Enable `~/.m2/repository` cache to speed-up build.
- [x] ~~Send code analysis report to SonarCloud (once).~~
- [ ] Send code coverage/analysis reports to SonarCloud only on branches. (check [here](https://github.com/carlspring/s3fs-nio/pull/77#issuecomment-686804207))
- [x] Setup matrices for ubutnu, windows and macos.
