### ISSUE TITLE
Improve file attribute caching

### ISSUE THREAD

**Issue by steve-todorov** [carlspring/s3fs-nio#854]
# Task Description

The current implementation of the file attribute caching is very basic and is still executing some REST API instead of hitting the cache. We need to improve this.

# Tasks

The following tasks will need to be carried out:
* [x] Use [Caffeine](https://github.com/ben-manes/caffeine/) for caching instead of re-inventing the wheel.
* [x] Replace and improve the file attribute cache implementation.
* [x] Ensure a test validates the cache is being used and works as expected.

# Task Relationships

This task:
* Is a sub-task of: #
* Depends on: #
* Is a follow-up of: #
* Relates to: #

# Useful Links

* [Caffeine](https://github.com/ben-manes/caffeine/)
* [Caffeine Docs](https://github.com/ben-manes/caffeine/wiki)
* [Caffeine Benchmarks](https://github.com/ben-manes/caffeine/wiki/Benchmarks)

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @steve-todorov
