### ISSUE TITLE
Investigate using `PutObjectRequest.html#ifNoneMatch`

### ISSUE THREAD

**Issue by steve-todorov** [carlspring/s3fs-nio#861]
# Task Description

In previous version of the AWS SDK v2 it was not possible to use a single request to put an object if the key did not exist.
With version 2.28+ you can use [PutObjectRequest.html#ifNoneMatch](https://sdk.amazonaws.com/java/api/2.28.0/software/amazon/awssdk/services/s3/model/PutObjectRequest.html#ifNoneMatch()) which would return a non 200 status code when there is an existing key.

If this works out it would improve the performance of the library as it would not be doing:

1. Head request to check if the object exists
2. Put request to actually add the object

Instead we'll be doing just one `PUT` request and handle the `status code`.

# Tasks

The following tasks will need to be carried out:
* [ ] Research how this works
* [ ] Investigate what we'll need to change to use it
* [ ] Implement a solution
* [ ] Test it out

# Task Relationships

This task:
* Is a sub-task of: #
* Depends on: #
* Is a follow-up of: #
* Relates to: #

# Useful Links

* [PutObjectRequest.html#ifNoneMatch](https://sdk.amazonaws.com/java/api/2.28.0/software/amazon/awssdk/services/s3/model/PutObjectRequest.html#ifNoneMatch())

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community)
* Points of contact:
  * @carlspring
  * @steve-todorov
